print("A Song of Ice and Fire".isupper())
print("A Song of Ice and Fire".islower())
print("A Song of Ice and Fire".upper())
print("A Song of Ice and Fire".lower())
print("A Song of Ice and Fire".istitle())
print("A Song of Ice and Fire".title())
print("A Song of Ice and Fire".startswith("A"))
print("A Song of Ice and Fire".endswith("e"))
print("A Song of Ice and Fire".split())
print(" ".join(['A', 'Song', 'of', 'Ice', 'and', 'Fire']).isalpha())
